name: Sync with Upstream

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Sync with Upstream
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git clone --bare https://github.com/lshbluesky/WhateverGreen.git upstream-bare
        cd upstream-bare
        git push --mirror https://x-access-token:${PAT}@github.com/lshbluesky/WhateverGreen-Mirror.git
